name: build_example_api

on:
  push:
    branches: [ main ]

env:
  CONTAINER_IMAGE: exampleapi
  CONTAINER_VERSION: 0.1.0
  REPOSITORY: ${{ secrets.REPOSITORY }}
  REPOSITORY_HOST: ${{ secrets.REPOSITORY_HOST }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build_example_api:
    runs-on: ubuntu-latest

    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go

      - name: checkout code
        uses: actions/checkout@v2

      - name: authenticate gcloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
        id: auth

      - name: setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - run: gcloud auth configure-docker $REPOSITORY_HOST

      - name: prepare release
        run: |
          mkdir -p latest
          echo "$CONTAINER_VERSION-$GITHUB_SHA" > latest/version.txt
      
      - name: build the ingress service
        run: |
          cd cmd/cdn
          go get -v -t -d ./...
          GOOS=linux GOARCH=amd64 go build -o svc main.go && chmod +x svc
      
      - name: build the cdn container
        run: |
          cd cmd/cdn
          docker build -t "$REPOSITORY_HOST"/"$REPOSITORY"/"$CONTAINER_IMAGE":"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
      
      - name: push the cdn container
        run: |
          docker push $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:$GITHUB_SHA
          docker tag $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:$GITHUB_SHA $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:latest
          docker tag $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:$GITHUB_SHA $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:$CONTAINER_VERSION
          docker push $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:latest
          docker push $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:$CONTAINER_VERSION